Host: {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vbXVzZXdlYXJhYmxlcy5jb20iLCJhdWQiOiJodHRwOi8vYXBpLm11c2V3ZWFyYWJsZXMuY29tIiwiZGF0YSI6eyJ1c2VySUQiOiI4YTk0MWFlZC04YWJlLTQ2ZjEtOTljMi05NjIxN2Q4OGJmMDgifSwiaWF0IjoxNjU5ODQwNDM0MDAwLCJleHAiOjE2NTk4NTI5MDUwMDAsInRpbWVab25lIjoiQXNpYS9Lb2xrYXRhIn0.eXRPWVUn7yE4H0TS2OyOqB5kNemg2eCupeRn88YMepQ
Content-Type: application/json
Content-Length: 91

{
    "updateObject": {
        "bedTime": "2022-08-07T08:16:02+5:30",
        "dataCollectionStep": 2
    }
}


response:

{
    "status": "success",
    "data": {
        "bedTime": "2022-08-07T11:45:05+05:30",
        "dataCollectionStep": 2
    },
    "message": "operation completed successfully",
    "displayMessage": "Successful"
}